name: Hugo Updater (WIP)
description: Update Hugo sites (WIP)
inputs:
  feed-url:
    required: true
    description: RSS feed URL
  readme-section:
    required: true
    description: README section
  max:
    default: 5
    description: RSS feed items
  template:
    default: '* [{{ title }}]({{ link }})'
    description: Markdown list item
  github_token:
    default: ${{ github.token }}
  branch:
    default: ${{ github.event.repository.default_branch }}
    description: Target branch to update.
  message:
    default: 'docs: update'
    description: Commit
runs:
  using: node20
  main: src/index.ts
branding:
  icon: activity
  color: red
